"""Single source of truth for the translated engine and C test oracle."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION = "3.53.4"
ARCHIVE_URL = "https://www.sqlite.org/2026/sqlite-amalgamation-3530400.zip"
ARCHIVE_SHA3 = "628a44cfe82c66aed1ccbbe85a562d2e33ebe64b3288981ed76285612227934e"
DEFINES = [
    "SQLITE_THREADSAFE=1",
    "SQLITE_USE_URI=1",
    "SQLITE_ENABLE_API_ARMOR",
    "SQLITE_ENABLE_BYTECODE_VTAB",
    "SQLITE_ENABLE_CARRAY",
    "SQLITE_ENABLE_COLUMN_METADATA",
    "SQLITE_ENABLE_DBPAGE_VTAB",
    "SQLITE_ENABLE_DBSTAT_VTAB",
    "SQLITE_ENABLE_EXPLAIN_COMMENTS",
    "SQLITE_ENABLE_FTS3",
    "SQLITE_ENABLE_FTS3_PARENTHESIS",
    "SQLITE_ENABLE_FTS4",
    "SQLITE_ENABLE_FTS5",
    "SQLITE_ENABLE_GEOPOLY",
    "SQLITE_ENABLE_MATH_FUNCTIONS",
    "SQLITE_ENABLE_NORMALIZE",
    "SQLITE_ENABLE_OFFSET_SQL_FUNC",
    "SQLITE_ENABLE_PERCENTILE",
    "SQLITE_ENABLE_PREUPDATE_HOOK",
    "SQLITE_ENABLE_RTREE",
    "SQLITE_ENABLE_SESSION",
    "SQLITE_ENABLE_SNAPSHOT",
    "SQLITE_ENABLE_STAT4",
    "SQLITE_ENABLE_STMT_SCANSTATUS",
    "SQLITE_ENABLE_STMTVTAB",
    "SQLITE_ENABLE_UNLOCK_NOTIFY",
    "SQLITE_SOUNDEX",
]
